### ISSUE TITLE
🌟 [EPIC] Styleguide Migration

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#2074]
> [<img alt="alina-beck" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/alina-beck) **Authored by [alina-beck](https://github.com/alina-beck)**
_<time datetime="2019-10-29T13:58:09Z" title="Tuesday, October 29th 2019, 2:58:09 pm +01:00">Oct 29, 2019</time>_

---

## :star2: EPIC – Styleguide Migration

We want to transition from relying on [Nitro Styleguide](https://github.com/Human-Connection/Nitro-Styleguide) to having all design tokens and components within our main repo. The following items need to be migrated:

### Design Tokens
- [x] icons
- [ ] logos
- [x] color: used ~ 52 times in 12 files
- [x] text-color: used ~ 13 times in 8 files
- [x] background-color: used ~ 20 times in 6 files
- [x] border-color: used ~ 4 times in 3 files
- [x] border-size: used ~ 6 times in 2 files
- [x] border-radius: used ~ 10 times in 7 files
- [x] font-size: used ~ 7 times in 5 files
- [x] font-space: used ~ 1 times in 1 file
- [x] font-family: used ~ 1 times in 1 file
- [x] font-weight: not used
- [x] line-height: not used
- [x] letter-spacing: not used
- [x] opacity: not used
- [x] space: used ~ 63 times in 14 files
- [x] size: used ~ 33 times in 2 files
- [x] box-shadow: used ~ 7 times in 6 files
- [x] duration: not used
- [x] ease: not used
- [x] z-index: used ~ 4 times in 4 files
- [x] media-query: not used

### Layout Components
- [x] ds-card: used ~ 55 times in 43 files
- [ ] ds-container: used ~ 20 times in 17 files
- [ ] ds-flex + ds-flex-item: used ~ 127 times in 31 files
- [ ] ds-grid + ds-grid-item: used ~ 9 times in 5 files
- [ ] ds-modal: used ~ 4 times in 4 files
- [x] ds-page: not used
- [x] ds-page-title: not used
- [ ] ds-placeholder: used ~ 2 times in 2 files
- [ ] ds-section: used ~ 6 times in 6 files
- [ ] ds-space: used ~ 112 times in 43 files
- [x] ds-spinner: used ~ 4 times in 3 files

### Typography Components
- [x] ds-chip: not used
- [x] ds-code: not used
- [ ] ds-heading: used ~ 20 times in 18 files
- [x] ds-icon: used ~ 33 times in 21 files
- [ ] ds-logo: used ~ 2 times in 2 files
- [ ] ds-tag: used ~ 4 times in 4 files
- [ ] ds-text: used ~ 66 times in 18 files

### Data Input Components
- [ ] ds-form: used ~ 14 times in 14 files
- [ ] ds-input: used ~ 39 times in 18 files
- [ ] ds-radio: used ~ 2 times in 2 files
- [ ] ds-select: used ~ 7 times in 6 files

### Data Display Components
- [x] ds-avatar: used ~ 2 times in 2 files
- [x] ds-copy-field: not used
- [ ] ds-list + ds-list-item: used ~ 10 times in 3 files
- [ ] ds-number: used ~ 15 times in 3 files
- [ ] ds-table: used ~ 5 times in 5 files
- [x] ds-button: used ~ 58 times in 43 files
- [ ] ds-menu: used ~ 8 times in 7 files

**Comment by Tirokk** [comment]
> [<img alt="stale[bot]" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/apps/stale) **Authored by [stale[bot]](https://github.com/apps/stale)**
_<time datetime="2020-05-10T17:04:18Z" title="Sunday, May 10th 2020, 7:04:18 pm +02:00">May 10, 2020</time>_

---


This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

**Comment by Tirokk** [comment]
> [<img alt="Mogge" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/Mogge) **Authored by [Mogge](https://github.com/Mogge)**
_<time datetime="2020-05-13T11:30:39Z" title="Wednesday, May 13th 2020, 1:30:39 pm +02:00">May 13, 2020</time>_

---


not stale

**Comment by Tirokk** [comment]
> [<img alt="stale[bot]" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/apps/stale) **Authored by [stale[bot]](https://github.com/apps/stale)**
_<time datetime="2020-07-12T11:49:27Z" title="Sunday, July 12th 2020, 1:49:27 pm +02:00">Jul 12, 2020</time>_

---


This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

**Comment by ulfgebhardt** [comment]
closing as completed
