### ISSUE TITLE
🌟 [EPIC] Comments

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#305]
> [<img alt="datenbrei" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/datenbrei) **Authored by [datenbrei](https://github.com/datenbrei)**
_<time datetime="2019-03-27T07:55:51Z" title="Wednesday, March 27th 2019, 8:55:51 am +01:00">Mar 27, 2019</time>_

---

### Comments

![image](https://user-images.githubusercontent.com/1238238/55495330-ec0fdd80-563c-11e9-8416-d1c13903680a.png)

- [X] Number of Comments
- [x] Write Comment
- [X] Author
- [x] Comment-Date
- [x] Mention another user with `@`
- [X] Text
- [x] Delete Comment #553
- [x] Update Comment #552
- [x] Send out mention notifications on CreateComment #1017
- [x] Send out create notifications on CreateComment to the Post author #1062
- [x] Expand and mark comment if one jumps to it by URL hashtag #1204
- [ ] Notify user when disabling a comment #276 
- [x] Mention button on each comment #1680 

💬 Question:
- [ ] Answer direct to a comment #2332 

🐛 Bugs:
- [x] Bugs in and Improvements for Comments #542 , #561

### Userstory
```gherkin
Feature: Comments
  As a user
  I want to comment on contributions of others
  In order to express my thoughts and emotions about these, discuss and add give further information.
```

### Design & Layout - Alpha

![image](https://user-images.githubusercontent.com/1238238/55495455-37c28700-563d-11e9-8b9c-d3f75d4e0ff5.png)
![image](https://user-images.githubusercontent.com/1238238/55495330-ec0fdd80-563c-11e9-8416-d1c13903680a.png)

### Design & Layout - Nitro

![image](https://user-images.githubusercontent.com/1238238/55495419-28433e00-563d-11e9-92d5-071869a463d2.png)

**Comment by Tirokk** [comment]
> [<img alt="Tirokk" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/Tirokk) **Authored by [Tirokk](https://github.com/Tirokk)**
_<time datetime="2019-04-15T15:29:29Z" title="Monday, April 15th 2019, 5:29:29 pm +02:00">Apr 15, 2019</time>_

---


# Upvote

Should it be possible in old Alpha Posts to up-vote comments?

Because no reply was possible, the order of the comments are in a kind of reply order.
Therefore I would suggest to disable the up-vote possibility in this case.

**Comment by Tirokk** [comment]
> [<img alt="ulfgebhardt" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/ulfgebhardt) **Authored by [ulfgebhardt](https://github.com/ulfgebhardt)**
_<time datetime="2019-04-16T11:24:02Z" title="Tuesday, April 16th 2019, 1:24:02 pm +02:00">Apr 16, 2019</time>_

---


Use the Editor Component

**Comment by Tirokk** [comment]
> [<img alt="stale[bot]" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/apps/stale) **Authored by [stale[bot]](https://github.com/apps/stale)**
_<time datetime="2019-11-19T20:09:52Z" title="Tuesday, November 19th 2019, 9:09:52 pm +01:00">Nov 19, 2019</time>_

---


This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

**Comment by Tirokk** [comment]
> [<img alt="stale[bot]" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/apps/stale) **Authored by [stale[bot]](https://github.com/apps/stale)**
_<time datetime="2020-02-09T10:21:41Z" title="Sunday, February 9th 2020, 11:21:41 am +01:00">Feb 9, 2020</time>_

---


This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

**Comment by Tirokk** [comment]
> [<img alt="Tirokk" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/Tirokk) **Authored by [Tirokk](https://github.com/Tirokk)**
_<time datetime="2020-03-06T07:46:35Z" title="Friday, March 6th 2020, 8:46:35 am +01:00">Mar 6, 2020</time>_

---


We keep it till the notification for disabling is done soon.

**Comment by Tirokk** [comment]
> [<img alt="stale[bot]" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/apps/stale) **Authored by [stale[bot]](https://github.com/apps/stale)**
_<time datetime="2020-05-05T10:58:17Z" title="Tuesday, May 5th 2020, 12:58:17 pm +02:00">May 5, 2020</time>_

---


This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

**Comment by Tirokk** [comment]
> [<img alt="Tirokk" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/Tirokk) **Authored by [Tirokk](https://github.com/Tirokk)**
_<time datetime="2020-05-07T11:05:36Z" title="Thursday, May 7th 2020, 1:05:36 pm +02:00">May 7, 2020</time>_

---


The two open checkboxes have to be fulfilled! 👆🏼

**Comment by ulfgebhardt** [comment]
closing as completed
