### ISSUE TITLE
🚀 [Feature] Upgrade to node 15.4

### ISSUE THREAD

**Issue by Mogge** [Ocelot-Social-Community/Ocelot-Social#4082]
## :rocket: Feature
It would be nice to have our code running on the latest node version (15.4 by now), which is not the case.
Known problems:
 * #4081 
 * #4068 (fixed)

Until these issues are not fixed. There is no way to update our node version.
May be there are more issues which have not been discovered yet.

### Todo

- [ ] Please make sure to update the backend/README.md when we upgrade our node version.
- [ ] And mention Node Version Manager `nvm` for the parallel installation of different node versions and thier usage in different folder/Terminals.
- [ ] `.nvmrc` files in the app folders can be helpful to quickly use the right Node version in a folder/terminal.

**Comment by Mogge** [comment]
Please make sure to update the `backend/README.md` when we upgrade our node version.
