### ISSUE TITLE
💥 [DevOps] EMail Server - On Digital Ocean using Docker

### ISSUE THREAD

**Issue by ulfgebhardt** [Ocelot-Social-Community/Ocelot-Social#4110]
## :fire: DevOps ticket

**EMail Server - On Digital Ocean using Docker**

We need an EMail Server on Digital Ocean as Docker to serve `@wir.social` EMails. This is required to change the Email of the admin accordingly and to send EMails from our Server.

What needs to be done:
- [ ] Clarify where we will have the EMail Server Sources located
      - [ ]  ocelot.social repo (NO!)
      - [ ]  wir.social branding repo (not sure)
      - [ ]  extra Repo just containing the docker file (recommended: we want to reuse the EMail Server for multiple domains within our juristriction)
- [ ] Clarify what Software to use
      - [ ]  Suggestion: https://github.com/tomav/docker-mailserver
- [ ] How do we administrate the Server? (I @ulfgebhardt need access to that)
- [ ] We need the server to answer to `@wir.social`
- [ ] We need the address `admin@wir.social` to be served and I need the credentials to that
- [ ] Do we need additional addresses?
- [ ] Can we wildcard all EMails to `admin@wir.social` ?
- [ ] What changes are needed on `ocelot` for this to work?

### Motive

Have a EMail Server in the same Infrastructure as we have all the other stuff. It needs to be able to serve multiple domains and administrating it should be easy.

### Implementation

Suggestion: https://github.com/tomav/docker-mailserver

### Validation

Minimum requirement: `admin@wir.social` must be served and accessable

### Additional context

This will be an Epic. Please open Tickets for the corresponding Tasks you intend to merge if needed.
Please merge anything that can go productive as soon as you can.
