### ISSUE TITLE
🌟 [EPIC] Extend Post Teaser And Embed Possibilities

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#4483]
## :rocket: Feature

We like to extent the post teaser and embed possibilities:

- radio streams
  - [ ] have embeds for radio streams like this: https://senderfm.out.airtime.pro/senderfm_a
- teaser image
  - [ ] have a list in the teaser image of:
    - all embeds images
    - several images dropped into it in the post creation process
- player in teaser image or instead with a standard teaser for radio or video streams
  - [ ] choose in the teaser list which embed shall be used as player and which embed or dropped teaser image should be used as teaser

### User Problem

- be flexible with the teaser image
- have the possibility to define radio streams as embeds
- can define a play on the teaser image as well

### Implementation

To define …

### Design & Layout

To define …

### Validation

None

### Additional context

None
