### ISSUE TITLE
🔧 [Refactor] E-Mail Templates To Be In A Single Language And Not Multi Language

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#4786]
## 🔧 Refactor

E-Mail templates to be in a single language and not multi language.
https://github.com/Ocelot-Social-Community/Ocelot-Social/tree/master/backend/src/middleware/helpers/email/templates

Have a look at the notifications template.
See: https://github.com/Ocelot-Social-Community/Ocelot-Social/blob/master/backend/src/middleware/helpers/email/templates/en/notification.html
And: https://github.com/Ocelot-Social-Community/Ocelot-Social/blob/master/backend/src/middleware/helpers/email/templates/de/notification.html

### Todo

- [x] moved to new issue #5461
  - [ ] think about leaving english as second and standard language in all templates which are not in english?
    - [ ] and add english then in the notifications template as second and standard language as well

**Comment by ibonkonesa** [comment]
Hi! Still open?

**Comment by Tirokk** [comment]
Hey @ibonkonesa ,

yes it's still open. You can take over. That’s great! 🤗
I assigned you to this issue.

I cared for your invitation to our community as volunteer via an e-mail invitation you can accept.

Our conversation runs over our discord server:
https://discord.gg/AJSX9DCSUA
There we have usually from Monday to Thursday a Daily Standup at UTC 09:30 am (CEST 11:30 am) in the Office Cube.

Please don’t compare from your fork to this repository, in case, because the publish GitHub Action will fail, because of permission problems with the credentials.
Just push your branch directly to our repo and compare to the master.
If you accept the invitation then you’ll have the right todo so. 😉

**Comment by Tirokk** [comment]
The ”think about“ in the discription should be moved to a question issue and not be part of this issue here anymore.
So just split english and german up if you like to.

**Comment by ibonkonesa** [comment]
What's exactly the point??

- Remove the Deutsch language mailing and ALL emails have to been sent in English 
or
- If user uses Deutsch language, send in Deutsch. Anyelse languages will be sent in English

**Comment by Tirokk** [comment]
> What's exactly the point??
> 
>     * Remove the Deutsch language mailing and ALL emails have to been sent in English
>       or
> 
>     * If user uses Deutsch language, send in Deutsch. Anyelse languages will be sent in English

We have only one e-mail separated in the to languages Deutsch and English:

- here: https://github.com/Ocelot-Social-Community/Ocelot-Social/blob/master/backend/src/middleware/helpers/email/templates/en/notification.html
- and here: https://github.com/Ocelot-Social-Community/Ocelot-Social/blob/master/backend/src/middleware/helpers/email/templates/de/notification.html

All the other e-mails in folder https://github.com/Ocelot-Social-Community/Ocelot-Social/blob/master/backend/src/middleware/helpers/email/templates are in Deutsch and English.

We like to separate them and put them in the two folders `templates/de/` and `templates/en/` like the notification e-mail is.
English is always the default language if the user language is not supported.

Just in case you are able and like to translate them just go ahead.

For sure you can just pickup one e-mail as a start and do as many you like to.

**Comment by ulfgebhardt** [comment]
closing as completed
