### ISSUE TITLE
🚀 [Feature] Improve e-mail deliverability with SPF and DKIM

### ISSUE THREAD

**Issue by sushidave** [Ocelot-Social-Community/Ocelot-Social#4845]
### Problem: 
A user of wir.social reported that an e-mail notification from the social network arrived in the spam folder of his GMX mail account.

Another user reported that she didn't get any e-mail notifications from the network in her mailbox of posteo.de. Spam folders don't exist at Posteo. Posteo notifies the sender the e-mail is classified as spam, see https://posteo.de/en/site/faq.

### Possible causes:
1. The sender domain of the network (freilernen.social, sender.fm, wir.social) and the server domain (mail.webcraft-media.de) are different and an SPF record in the DNS zone of wir.social is missing.
2. Messages are not signed with DKIM and no public key for DKIM is available in the DNS zone.

### Tasks:
- [ ] Add SPF record to DNS zone of wir.social.
- [ ] Sign outgoing messages with DKIM, see https://nodemailer.com/dkim/, and add public key in DNS zone.
- [ ] Consider the same for other ocelot.social networks.
- [ ] Add this recommendation to the documentation.

@Tirokk @Raimundo-dev

**Comment by Tirokk** [comment]
Hey @ulfgebhardt ,
how we can handle this?

**Comment by ulfgebhardt** [comment]
This should fixed
