### ISSUE TITLE
💥 [DevOps] Implement General Logging Like 'log4js'

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#5039]
## 💥 DevOps Ticket

Implement general logging like 'log4js', see Gradido project: https://github.com/gradido/gradido/blob/master/backend

### Todo

- [ ] implement general logging like 'log4js'
  - [ ] see Gradido project: https://github.com/gradido/gradido/blob/master/backend
- [ ] disable e-mail logging on database seeding?
