### ISSUE TITLE
🌟 [EPIC] Release v2.0.0 In Groups Branch - Group: For Groups/Organisations/Projects - Subset Of Former Orgs EPIC Named Group Now Instead Org

### ISSUE THREAD

**Issue by ogerly** [Ocelot-Social-Community/Ocelot-Social#5059]
## 🌟 EPIC

——— This issue is is a subset of the EPIC #4544 ———

### General Concept

A group is the very general concept for every entity which is not a person – a group of people, an organisation, a business, a project, a charity, a foundation ...

Implement a feature called `group` means to create a new entity which is not a user account and therefore can not be logged in. But it has a group profile similar to a user profile, see below.

#### New `My Groups Page`

→ [more details](#user-content-my-groups-page)

Reach the `my groups` page:

- [x] New menu item `My groups`: ( #5395 )
  - [x] Chose this user menu of the header will open the page.

<img width="303" alt="Bildschirmfoto 2022-07-23 um 05 43 09" src="https://user-images.githubusercontent.com/25344101/180589335-7715d341-824b-4bca-be14-512da5d6e0fc.png">

##### Configurable Additional Options In Header

Option 1:

- [x] New icon with 2 people in a circle: (3 people would be more look like a group says @LarsE11 and @Tirokk agrees)
  - [x] Klick on this icon ([source stylguide](https://styleguide.human-connection.org/typography/dsicon)) in the header on the right hand between the language and the bell will open the page.

(see issue #5395 )

<img width="372" alt="Bildschirmfoto 2022-07-23 um 05 26 14" src="https://user-images.githubusercontent.com/25344101/180588868-585657dc-bb33-4b4c-9cd2-89b58f70b310.png">
<img width="415" alt="Bildschirmfoto 2022-07-23 um 05 30 59" src="https://user-images.githubusercontent.com/25344101/180589005-ad031f47-27c8-4628-bc55-de08bf2827b4.png">

Option 2:

( @LarsE11 and @UlfTramsen wish and it seem nice to have the possibility)

- [x] Configurable quick click menu between header logo on the right and the search field.
  - [ ] Maybe make the search field smaller:
    - [ ] May expand it if the cursor fokus is in it (or have just a lupe and make the search field animated expanding if you click it)
- [x] Have `Groups` or `My Groups` there as a text menu item.

<img width="1225" alt="Bildschirmfoto 2022-07-26 um 05 44 47" src="https://user-images.githubusercontent.com/25344101/180918589-32178b25-c88c-4b9a-8d42-153c50c36d8c.png">

#### New Group Profile Page

→ [more details](#user-content-group-profile-page)

The group profile page can be reached by:

- [x] via the list on the `my groups` page
- [ ] via the groups list on a users page
- [ ] click on avatar or slug-name of a group, may be on a post or in a list
- [ ] via the search in the header search field ( #5394 )
  - [ ] specific search groups with `&…`

### Group Types <a href="#user-content-group-types" id="group-types">#</a>

There will be the types:

- [public](#user-content-public-group)
- [closed](#user-content-closed-group)
- [hidden](#user-content-hidden-group)

### Public Group <a href="#user-content-public-group" id="public-group">#</a>

- Every registered user can read everything.
- Only group members can post/comment in the group.
- Of course you can leave the group at any time.
- Group members are visible for all registered users.
- By clicking on a button "Become a member" you immediately become a group member (without extra permission)
  - that should be a [setting](#user-content-group-settings) of the admin ( @Tirokk asks) (Yes, good idea @LarsE11 )

### Closed Group <a href="#user-content-closed-group" id="closed-group">#</a>

- Content (e.g. posts) is readable for group members only.
- The group page is only visible and searchable for registered users.
- Either by invitation or by clicking the button "Become a member".
- Membership must be confirmed by a group admin. (high effort! because of the notification)
- Group admin can decide if group members are visible for all registered users or only for group members.

### Hidden Group <a href="#user-content-hidden-group" id="hidden-group">#</a>

- The group page and all content is visible ONLY to group members.
- You can become a member ONLY by invitation.

### My Groups Page <a href="#user-content-my-groups-page" id="my-groups-page">#</a>

→ More details, see issue #5140 and PR #5148 .

Reach the `my groups` page under the path `domain.social/mygroups`.

On this page you find:

- One list of the groups you own (maybe administer) and where you are a member.
  - Have visual sign for your owned groups.
- An add button to create a new group.

List view:

- It's a list of group cards. (like our post cards)
- A group card shows a short form of the group informations.

Functionallities of a group card: (list item)

- Click on group card links to the [group profile](#user-content-group-profile-page).
  - On the group profile you can reach the [group settings](#user-content-group-settings) via the context menu.
- (later?) Context menu directly on the post card
  - As it is on the [group profile](#user-content-group-profile-page).

### Group Settings Page <a href="#user-content-group-settings" id="group-settings">#</a>

Sub issues:

- [x] #5131

The group settings are on two new pages located on the paths:

- Create with group settings: `domain.social/group/create`
- Edit group settings : `domain.social/group/edit/ID`

Properties:

- A group has one admin/owner. (later more admins)

You'll have the following settings for a group:

#### For Admins

- name/title (unique)
- slug-name (unique)
- goal of the group, what's it for?
- [group type](#user-content-group-types)
  - can be changed only in direction of higher invisibility, see issue #5387
    - public → closed → hidden
- action radius
  - local/regional
  - national
  - continental
  - international
- location (for action radius: set optional)
- categories: 1-3
- manage membership, see issue #5386
  - needs permission by the admin (checkbox)
  - member list is group external visible (has public group this setting asks @Tirokk or always visible?) (yes says @LarsE11 )
- delete group button, see issue #5388
  - shows confirmation modal
- members list (admin view)
  - membership
    - pending membership (waits for acceptance)
      - may an admin can set the membership later again to pending?
    - accepted membership
  - roles #5189 
    - usual member
    - admin (later more than one)
    - owner (later more than one?)
    - moderator (later, for now only the network moderators and admins can moderate)
  - remove a member, see issue #5389
    - with reason (later)

### Group Profile Page <a href="#user-content-group-profile-page" id="group-profile-page">#</a>

→ [more details](https://github.com/Ocelot-Social-Community/Ocelot-Social/pull/5197)

Reach the group profile page under the path:

- short form: `domain.social/group/group-slug`
- long and permanent form: `domain.social/group/ID/group-slug`
  - The ID identifys the group permanently, even if its slug-name changes.

A groups profile page is kind of similar to a users profile page.

On entering the page:

- No members: Seeing the group description.
- Memebers: Seeing the groups post feed.

#### Group Profile Content

→ [more details](https://github.com/Ocelot-Social-Community/Ocelot-Social/issues/5318)

- at the top
  - banner (later, set optional, see issue #397, PR #3634 )
- top box left side
  - logo or avatar icon (set optional)
    - drag & drop
    - file dialog on click
  - "⠇" context menu with:
    - [Group settings](#user-content-group-settings) (admin/owner of the group)
  - name/title (unique)
  - slug-name (unique)
  - group type
  - goal of the group, whats it for?
  - location of group
  - categories
  - button: `Apply for membership` / `Get member` / `Withdraw membership application` / `Leave group`
- second box left side
  - member list (only public groups)
- right two columns
  - expandable description
    - suggestion, see [Design Drafts For Group Profile](#user-content-design-drafts-for-group-profile)
    - rich design like a post with:
      - headlines, bold, italic etc.
      - links
      - video embeds
  - tab bar gets removed (agreed @LarsE11 @Mogge @Tirokk )
  - post feed, see #5385
    - non-members see no post feed (later we may have group internal and group external posts?)
    - comments gets removed (agreed @LarsE11 @Mogge @Tirokk )
    - shouts/likes gets removed (agreed @LarsE11 @Mogge @Tirokk )
      
##### Suggestions

Description replaces the tabs:

<img width="1646" alt="Bildschirmfoto 2022-07-25 um 18 13 56" src="https://user-images.githubusercontent.com/25344101/180826752-44a8153a-296b-46db-bf22-749cbfea718b.png">

#### Moderation

- Every user can report a group with a reason.
- Network moderators/admins can make groups invisible.

##### Questions

- What can admins or owners do? See issue #5386
  - Admin:
    - What is an admin allowed todo?
      - Confirm pending members?
      - Removing members from group?
  - Owner:
    - Leaving the group:
      - If there is another owner?
- If I'm not allowed seeing the group members:
  - can i see the members count?
    - or shall the admin say if or of not?

#### Posts And Categories

- Creating a post in a group will overtake its categories as suggestion.

#### Newsfeed

Directly after login the newsfeed will visible. (already happens)

There will be shown:

- Internal public (registered users) posts.
- Posts of my groups.

##### Post Page

Shows:

- &group-name
- @author

##### Post Card (short form of a post)

Shows:

- &group-name

On klick of it you go to the post page. (already happens)

### Network Configuration

- switch groups on and of

### Further Planning for later: List Of Ideas And Questions

Can only administrators create groups?

- What about the moderation of closed groups?
  - Can all Network moderators moderate them?
- Administrators can turn all groups on and off?
 
#### Actions as user

- [x] user can create an org
- [x] user can see an orgs profile
- [ ] user can search for orgs
- [ ] user can follow orgs (?)
- [x] user can become a member (different settings required: invite, request, free join)
- [ ] user can see additional infos (in which circumstances? @ulfgebhardt as member?)
- [x] user can read project posts

#### Actions as owner or admin

- [x] owner/admin can delete org
- [x] owner/admin can post as org
- [x] owner/admin can change org settings
- [ ] owner/admin can set/change additional info
- [ ] owner/admin can invite/set roles of members

#### Actions as network admin

- [ ] switch orgs on and off

#### Open questions and outlooks

- [ ] rights management (what roles? how? when? whom?)
- [ ] Do we allow follow like on the user profile?
- [ ] Can only orgs follow orgs?  (no: we need a concept how to connect orgs)
- [ ] Can users follow orgs?
- [ ] group chats of members (we have to recognise that posts are not the same as chat messages even when the comment function of a post is often used like a chat by the users)

### User Stories

As a Creator

- [x] I want to create an org
- [x] I want to view a Group
- [x] I want to delete a Group
- [x] I want to post as a Group
- [x] I want to publish some general persistent Info about the Group
- [x] I want to administer a Group
- [x] I want to invite others to the Group
- [ ] I want to give other access to the Group
- [x] I want to kick members from the group
- [ ] I want to administer the members of my Group
-[ ]  I want to transfer ownership of the Group

As a User

- [x] I want to view a Group
- [x] I want to see other Posts of a Group
- [ ] I want to find out who's behind that Group/posting as that Group
- [ ] I want to join a Group

As a Moderator of the Network

- [ ] I want to view all contents of a Group
- [ ] I want to block a Group as a whole
- [ ] I want to block single Posts of a Group
- [ ] I want to administer the Group(?)
- [ ] I want to administer the members of a Group(?)
- [ ] I want to change ownership of a Group
- [ ] I want to force a name change on a Group
- [ ] I want to remove some or all of the static content of a Group

Suggested initial Order of Implementation:

- [x] I want to create a Group
- [x] I want to view a Group
- [x] I want to delete a Group
- [x] I want to publish some general persistent Info about the Group
- [x] I want to post as a Group

**Comment by sushidave** [comment]
@Tirokk FYI - Table for group types, visibility, permissions and options added.

**Comment by Tirokk** [comment]
The wish of Yunite is to explicitly to name it `Goal` and not `About us` @sushidave .

**Comment by Tirokk** [comment]
I do not wanted to close this
