### ISSUE TITLE
🌟 [EPIC] Refactor Deployment And Add Documentation

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#5067]
## 🌟 EPIC

Refactor deployment and add documentation.

- [x] refactor Docker images of `webapp` and `backend` to run in our cluster without errors on start
  - [x] *main code repo:* #5066
- [x] Rename `ocelotsocialnetwork/neo4j:<VERSION_TAG>` To `ocelotsocialnetwork/neo4j-community:<VERSION_TAG>`
  - [x] *main code repo:* #4472
  - [x] *deploy repo:* https://github.com/Ocelot-Social-Community/Ocelot-Social-Deploy-Rebranding/issues/18
- [x] Change image Entries In Docker Compose Files And Get Apple M1 Running #5072
  - [x] *main code repo:* #5073
  - [x] *deploy repo:*
    - [x] *deploy repo:* https://github.com/Ocelot-Social-Community/Ocelot-Social-Deploy-Rebranding/pull/49
    - [x] https://github.com/Ocelot-Social-Community/Ocelot-Social-Deploy-Rebranding/issues/54
- [x] rename maintenance container from `maintenance` to `container-ocelot-maintenance`
  - [x] *main code repo:* #5065
  - [x] *deploy repo:* https://github.com/Ocelot-Social-Community/Ocelot-Social-Deploy-Rebranding/issues/48
- [x] refine deployment setup and documentation
  - [x] *deploy repo:* https://github.com/Ocelot-Social-Community/Ocelot-Social-Deploy-Rebranding/pull/46
- [x] docu: add live demo and networks in use list
  - [x] *main code repo:* #5064
  - [x] *deploy repo:* https://github.com/Ocelot-Social-Community/Ocelot-Social-Deploy-Rebranding/pull/46
- [ ] pull important docker images from the original source and push them to our repositoy
  - [ ] *main code repo:* #5077
- [x]  fix Automatic Deployment To stage.ocelot.social On Push To master Branch 
  - [x] *main code repo:* #5093
- [ ] shall `AppVersion` in `deployment/kubernetes/Chart.yaml` be really `latest`?
  - [ ] *deploy repo:* https://github.com/Ocelot-Social-Community/Ocelot-Social-Deploy-Rebranding/issues/47

**Comment by Tirokk** [comment]
All last open stuff is in issues
