### ISSUE TITLE
💥 [DevOps] Pull Important Docker Images From Original Source And Push Them To Our Repositoy

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#5077]
## 💥 DevOps Ticket

Pull important docker images from the original source and push them to our repositoy.

### Todo

- [ ] pull `node:12.19.0-alpine3.10`
  - [ ] push it to our Docker repo
  - [ ] save it in our backup
- [ ] pull `neo4j:3.5.14`
  - [ ] push it to our Docker repo
  - [ ] save it in in our backup
- [ ] pull `djfarrelly/maildev`
  - [ ] push it to our Docker repo
  - [ ] save it in in our backup
