### ISSUE TITLE
🚀 [Feature] Implement Group GraphQL Model And CRUD Resolvers In Backend

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#5131]
## :rocket: Feature Request

Implement group GraphQL model and CRUD resolvers.

- relates #5059

### Todo

- [x] GraphQL
  - [x] add group settings ( details see https://github.com/Ocelot-Social-Community/Ocelot-Social/issues/5059#user-content-group-settings )
    - [x] owner/admin
    - [x] name (title)
    - [x] slug-name
    - [x] about (goal)
    - [x] description:
      - [x] minimal 100 chars
    - [x] group type
    - [x] action radius
    - [x] location
    - [x] categories: 1-3
    - [x] add relation `CREATED`
  - [x] rename `UserGroup` to `UserRole`
  - [x] define resolver for:
    - [x] `CreateGroup`
      - [x] error on name length, see frontend
    - [x] `Group`
    - [x] `UpdateGroup`
    - [x] `DeleteGroup`, see #5388
- [x] seeding:
  - [x] seed a group

**Comment by Tirokk** [comment]
solved
