### ISSUE TITLE
🚀 [Feature] Implement Group GQL Model And CRUD Resolvers – Update Resolver

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#5222]
## :rocket: Feature Request

Implement group GQL model and CRUD resolvers – update resolver.

- relates #5131
- relates #5059

### Todo

- [x] @Mogge suggestions:
  - [x] `international` → `global`
  - [x] remove `wasSeede`
- [ ] GraphQL
  - [ ] add group settings ( details see https://github.com/Ocelot-Social-Community/Ocelot-Social/issues/5059#user-content-group-settings )
    - [x] owner/admin
    - [x] name (title)
    - [x] slug-name
    - [x] about (goal)
    - [x] description:
      - [x] minimal 100 chars
    - [x] group type
    - [x] action radius
    - [ ] location
    - [x] categories: 1-3
    - [x] add relation `CREATED`
  - [x] rename `UserGroup` to `UserRole`
  - [ ] define resolver for:
    - [ ] `AvailableGroupTypes`
    - [ ] `AvailableGroupActionRadii`
    - [ ] `AvailableGroupMemberRoles`?
    - [ ] `UpdateGroup`
    - [ ] `DeleteGroup`
  - [ ] `Deletable`:
    - [ ] What happens with their groups if users deletes their user profile?
- [x] resolvers:
  - [x] CreateGroup:
    - [x] test correct slugification
  - [x] check for tests in:
    - [x] backend/src/middleware/permissionsMiddleware.spec.js
    - [x] backend/src/middleware/slugifyMiddleware.spec.js
- [ ] seeding:
  - [ ] seed a group
- [x] Neo4j database:
  - [x] how to add a `slug` contraint for `Group` label?
    - [x] where is the `slug` contraint for `Post` and `User` label? See `backend/src/db/migrate/store.js`
- [x] cleanup: search for `Wolle`

**Comment by Tirokk** [comment]
Closed, because the next step relates to the same issue
