### ISSUE TITLE
🔧 [Refactor] Does Avatar Testing In Backend Make Sense This Way?

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#5256]
## 🔧 Refactor

Does avatar testing in backend makes sense this way?

The missing `await` can be one reason for flaky backenend tests!?

### Todo

- [ ] does avatar testing make sense this way in `backend/src/schema/resolvers/user_management.spec.js`
  - [ ] minimum: await is missing … or?
  - [ ] search for other appearances of `avatar: Factory.build('image',` or `Factory.build('image'` without aw

- related #4572
