### ISSUE TITLE
🚀 [Feature] Implement Group Profile – Next Steps

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#5318]
## :rocket: Feature Request

Implement group profile – second step.

### Todo

- [x] member list
- [x] member count
- [x] join group button
- [x] leave group button
- [x] group type
- [x] action radius
- [x] my role
- [x] description
- [x] group location
- [ ] content menu
  - [x] show profile, settings ( #5419 )
  - [ ] report group ( #5449 )
- [x] categories
- [ ] avatar
  - [ ] is updating after upload? followup issue #5510
- [ ] invite button – followup issue #5511
- [ ] social-media
  - [x] created issue, see #5409 
- [x] tabs – removed
- [ ] test
  - [ ] backend
    - [ ] can only the users thierself join a group like via leave?
- [ ] does image upload on post still work?
- [x] `hidden` groups can only be seen by members that are not `pending`
- [ ] cleanup:
  - [ ] view comments in `webapp/pages/group/_id/_slug.vue`
  - [ ] search `Wolle`

**Comment by Tirokk** [comment]
created followup issues
