### ISSUE TITLE
🚀 [Feature] Refine Group Creation And Group Edit

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#5397]
## :rocket: Feature Request

Refine group creation and group edit.

### Todo

- [x] group icon on left side in header configurable (maybe three people)
- [ ] fields:
  - [x] general validation for all fields like on post
  - [ ] slug:
    - [ ] change does not work like expected
      - [ ] backend is involved
      - [ ] discuss with @Mogge and @ogerly how it should work
    - [x] created an issue #5480
  - [x] goal:
    - [x] add placeholder
  - [x] description:
    - [x] add placeholder
    - [x] add char counter like on post content
    - [x] tiptap editor
  - [x] locationName:
    - [x] have a clear button like in the search select in the header to empty the field
  - [x] Translation 
    - [x] translation input selects group radius and group type

**Comment by Tirokk** [comment]
Is fullfilled by #5418
And for the remainders we have #5480
