### ISSUE TITLE
🚀 [Feature] Group Administration

### ISSUE THREAD

**Issue by ogerly** [Ocelot-Social-Community/Ocelot-Social#5406]
## :rocket: Feature Request

Implement group administration.

### Todo

- [ ] Create a page in the admin area for the general group settings.
- [ ] Create a new point in the database for the property boolean.
- [ ] Create a property that can switch the creation of new groups by users on and off.
- [ ] member role rights:
  - if I'm not allowed seeing group members
    - [ ] can I see the the members count on the groups profile?

**Comment by Tirokk** [comment]
is closed in favor of #5386
