### ISSUE TITLE
💥 [DevOps] Check Resolvers For Savetyness

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#5462]
## 💥 DevOps Ticket

Check resolvers for savetyness.

### Todo

- [x] change `Notfication` → `Notification`
- [ ]  make ticket to refactor shield middleware
- [x] comment on hidden post(group) possible via API ?
