### ISSUE TITLE
🔧 [Refactor] Edit Slug Of Group Does Not Work Like Expected

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#5480]
## 🔧 Refactor

Edit slug of group does not work like expected.

We have to discuss this I guess. @Mogge @ogerly @ulfgebhardt 

### Todo

- [x] backend:
  - [x] `sluggifyMiddelware`
  - [x] test:
    - [x] `src/middleware/slugifyMiddleware.spec.js`
    - [x] `src/schema/resolvers/groups.spec.js`
- [x] webapp:
  - show if slug of group already exists?
  - created a new issue #5595
- [x] cleanup: search for `Wolle`
