### ISSUE TITLE
🐛 [Bug] On Group Profile Avatar Does Not Update After Upload

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#5510]
## :bug: Bug Report

On group profile avatar does not update after upload.

### Todo

- [x] avatar
  - [x] is updating after upload?
- [x] description on group profile page changes unintendedly
  - [x] if I drop an avatar in the avatar image the `grouDescriptionExcerpt` changes
    - [x] happens on seeded group `Investigative Journalism`
    - [x] a look into the database shows that `grouDescriptionExcerpt` is empty now
