### ISSUE TITLE
🚀 [Feature] Yunite — Button `Please read the new terms of use now` Shall Be Configurable To Point To External Page

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#5618]
## 🚀 Feature

Button `Please read the new terms of use now` shall be configurable to point to external page.

See screenshot:

<img width="1646" alt="Bildschirmfoto 2022-10-31 um 14 47 34" src="https://user-images.githubusercontent.com/25344101/199025534-96c47ebc-a9c7-4518-adbe-3f366a561d28.png">

### Todo

- [ ] use the data which are used for the footer link to the same page
  - see the donation button
- [ ] use as well the configuration that opens the external page on a new tab or page
  - property: `target`
- [ ] add this to the deployment issue for the next yunite release
  - this is not needed for the ocelot.social deploy/rebranding repo I guess

**Comment by nishtha53** [comment]
can i work on this issue?
