### ISSUE TITLE
🚀 [Feature] Geolocation – Map To Show Locations Of Users And Groups

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#5807]
## 🚀 Feature

Geolocation – Map To Show Locations Of Users And Groups.

```gherkin
Feature: Map for users and groups
  As a user
  Do I want to find other users and groups in my area or in other places I travel to or the like.
```

### Todo

- [x] we like to have an additional page with a map
  - [x] map shall be reached by globus in header menu
    - [x] the one of the language menu
      - [ ] in the size of the avatar image
      - [x] tooltip:
        - de: `Landkarte anzeigen`
        - en: `Show map`
    - [ ] do we use a different icon in the language menu then?
- [x] chose map service:
  - [x] services:
    - [x] MapBox
      - @ulfgebhardt @ogerly @Tirokk decided for the package `v-mapbox`: https://github.com/geospoc/v-mapbox
    - [ ] Open Street Map
  - [x] comparison:
    - [x] https://www.rst.software/blog/google-maps-vs-mapbox-vs-openstreetmap-which-map-api-should-you-choose-and-why
- [x] have a search field above the map to enter the location to be shown
  - [x] search field is now in the map
    - [ ] label:
      - [ ] de: `Suchort oder -region eingeben`
      - [ ] en: `Enter search city or region`
  - [x] the location shall start at my own location
    - [x] if I have not entered my own location in the settings what happens then?
      - we start in Germany now and change that in the future
- [x] the map shall show flags or pins in different colors:
  - [x] users
  - [x] groups
- [x] map functionallities:
  - [x] zoom in and out
  - [x] move map with mouse
  - [x] hover over flag shows popup with name of user or group
    - [x] click routes to user or group profile
    - [x] similar to https://www.kartevonmorgen.org/
- [x] (see follow up issue #5901 ) map visibility (for later):
  - [x] even if a user is not logged in somehow defined users and groups can be seen on the map, followup see: #5928
- [x] if I don't want to be visible on a map as user
  - [x] I should not enter my location in the settings?
    - [x] may have a hint in the settings that by entering my location I a gree to show my location on the map
    - [x] and maybe hint that the position is not very specific
  - [x] (nope) or do I have to have a checkbox in the settings?
- [x] (see follow up issue #5901 ) to make the position a little more precise, especially in large cities, create the possibility of entering the postal code or a district of the city

### Issues

- relates #4546
