### ISSUE TITLE
🚀 [Feature] Map – Optimizations

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#5901]
## 🚀 Feature

Map – Optimizations.

### Todo

- [ ] map optimization:
  - [ ] have nicer marker?
    - [ ] the loaded is not the one used by default markers
      - what you can see if you enter a location in the search
    - [ ] may be as SVG, but this must be added by another technic
  - [ ] divers warnings in the browser console
  - [ ] optimize overlap
