### ISSUE TITLE
👑 [Release] Release v2.5.0

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#5908]
## 👑 Release

Release v2.5.0

### Todo

- [x] #6037
- [x] #6030
- [x] we like to redefine `$color-secondary` in Yunite: rebranding: https://github.com/Yunite-Net/Yunite-Net-Ocelot-Social-Deploy-Rebranding/pull/31
  - [x] search where `$color-secondary` is used and if that's fitting
- [x] #5689
- [ ] https://github.com/Ocelot-Social-Community/Ocelot-Social-Deploy-Rebranding/issues/102
- [x] test viewport on Android:
  - [x]  #5627
