### ISSUE TITLE
🚀 [Feature] Backend, DB – Add `Event` like `Post` for neo4j

### ISSUE THREAD

**Issue by Elweyn** [Ocelot-Social-Community/Ocelot-Social#6043]
## 🚀 Feature
Create an Event as a special Post with additional informations, so we can use the already defined Post functions.
Extra informations:
- label "Event"
- location type
  - online event
  - geolocation
- start date and time
- end date and time

## Todo
- [x] Migration for all existing Posts to add additional label "Article"
- [x] Create Post Mutation needs a new Enum parameter to define if it creates an Article or an Event
  - [x] Add label "Post" and label ("Event" or "Article")
- [x] Update Post Mutation change second label "Event" to "Article" or "Article" to "Event"
