### ISSUE TITLE
💥 [DevOps] migrate Cypress to current version 12

### ISSUE THREAD

**Issue by mahula** [Ocelot-Social-Community/Ocelot-Social#6118]
## 💥 DevOps ticket
For end-to-end testing Cypress version 7 is in use.
We should migrate to the current version 12.

### TODO
- [x] upgrade Cypress version 
- [x] migrate cucumber preprocessor to [@badeball/cypress-cucumber-preprocessor](https://github.com/badeball/cypress-cucumber-preprocessor)
- [x] migrate configuration JSON to Javascript
- [x] change test directory structure from `integration` to `e2e` 
- [x] fix Cypress issue with finding model definitions for factories

**Comment by mahula** [comment]
@roschaefer,

for the Cypress migration to version 12 most things are done.
There is still a problem with seeding at this point, which you once commented on regarding Cypress and the `fs` module.

Here is the error message (regarding [backend/src/models/index.js](https://github.com/Ocelot-Social-Community/Ocelot-Social/blob/cypress-migrate-to-v10/backend/src/models/index.js))

> The following error originated from your test code, not from Cypress.
> Couldn't find a definition for "Image". It looks like no models have been defined.

All changes can be found in [this PR](https://github.com/Ocelot-Social-Community/Ocelot-Social/pull/6008).

To run a simple test run in the project's root directory
`yarn run cypress run --browser electron --e2e --config-file ./cypress/cypress.config.js --spec ./cypress/e2e/User.Authentication.feature`

Could you please have look and help out solving this issue?
