### ISSUE TITLE
🚀 [Feature] Register an Inbox at Say Thanks

### ISSUE THREAD

**Issue by sushidave** [Ocelot-Social-Community/Ocelot-Social#6119]
## 🚀 Feature

Create an inbox at [Say Thanks](https://saythanks.io/) for people to send a thank you to the developers.

### Tasks
- [ ] Register an inbox at [saythanks.io](https://saythanks.io/)
- [ ] Publish the link in the README.md of Ocelot
- [ ] Publish the link in the wiki of Ocelot
- [ ] Publish the link on Ocelot website
- [ ] Publish the link on busFaktor() website
- [ ] Publish the link on busFaktor()'s YouTube channel and video descriptions
- [ ] Publish the link on busFaktor()'s user profile page in Ocelot networks
- [ ] Publish the link on posts in Ocelot networks
- [ ] others?

As discussed with @Tirokk.
