### ISSUE TITLE
🚀 [Feature] Webapp – Add Tooltips to All Menu Icons

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#6184]
## 🚀 Feature

Webapp – Add Tooltips to All Menu Icons.

### Todo

Tooltip text for all menus:

- [x] language select:
  - [x] EN: `Choose language`
  - [x] DE: `Sprache wählen`
- [x] notifications:
  - [x] EN: `My notifications`
  - [x] DE: `Meine Benachrichtigungen`
- [x] invite friends:
  - [x] EN: `Invite friends`
  - [x] DE: `Freunde einladen`
- [x] show groups:
  - [x] EN: `﻿Show groups`
  - [x] DE: `Gruppen anzeigen`
- [x] show map: (perfekt already)
  - [x] EN: `﻿Show map`
  - [x] DE: `Landkarte anzeigen`
- [x] my profile:
  - [x] EN: `My profile`
  - [x] DE: `Mein Profil`
- [x] check for mobile
