### ISSUE TITLE
🚀 [Feature] Webapp: Event create design optimization

### ISSUE THREAD

**Issue by Elweyn** [Ocelot-Social-Community/Ocelot-Social#6266]
## 🚀 Feature

On the page create event we need some design optimization. 
- The tab selection is not optimal
- The date-picker could be grayed out, mark the current date, 
- Start date has no default

## 🤖 Todo
- [ ] datepicker (ausgrauen, markein aktuelles Datum)
- [ ] Auswahl zwischen Post/Event nicht schön
- [ ] Required feld für Start Zeitpunkt enhält keinen Text
