### ISSUE TITLE
🚀 [Feature] Frontend: Create a vue-advanced-chat component

### ISSUE THREAD

**Issue by Elweyn** [Ocelot-Social-Community/Ocelot-Social#6398]
## 🚀 Feature
https://github.com/antoine92190/vue-advanced-chat
```Vue
<template>
  <vue-advanced-chat
    :current-user-id="currentUserId"
    :rooms="JSON.stringify(rooms)"
    :messages="JSON.stringify(messages)"
    :room-actions="JSON.stringify(roomActions)"
  />
</template>

<script>
  import { register } from 'vue-advanced-chat'
  register()

  // Or if you used CDN import
  // window['vue-advanced-chat'].register()

  export default {
    data() {
      return {
        currentUserId: '1234',
        rooms: [],
        messages: [],
        roomActions: [
          { name: 'inviteUser', title: 'Invite User' },
          { name: 'removeUser', title: 'Remove User' },
          { name: 'deleteRoom', title: 'Delete Room' }
        ]
      }
    }
  }
</script>
```

## 🤖 TODO
- [ ] Implement the necessary functions 
  - no ``roomActions`` in the first step
- [ ] Add something to show that there is an unread/new message
- [ ] Field to add a new message to the room
