### ISSUE TITLE
🚀 [Feature][Frontend] Chat: Change design and language to ocelot-design

### ISSUE THREAD

**Issue by Elweyn** [Ocelot-Social-Community/Ocelot-Social#6400]
## 🚀 Feature

![image](https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/33051975/ed592a3e-2a02-4294-8f81-1b602f224244)

## 🤖 TODO

- [x] Change the style to the ocelot.social style
- [x] Change multi language
- [x] Adjust chat slots to fit with the ocelot.social style
