### ISSUE TITLE
🐛 [Bug] Yunite – Webapp – Registration – Terms and Condition + Data Privacy Links Going to Internal Pages

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#6439]
## 🐛 Bugreport

Yunite – Webapp – Registration – Terms and Condition + Data Privacy Links Going to Internal Pages instead to the yunite.org link of the footer.

<img width="655" alt="Bildschirmfoto 2023-06-13 um 22 18 16" src="https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/25344101/9930ca5d-f94e-4683-8544-b59013fb2e1b">

### Todo

- [x] prepare in main code: #6441
- [x] define in stage.yunite.me and yunite.me branding code:
  - [x] https://github.com/Yunite-Net/stage.yunite.me/commit/bb0574d733ab28c37ac65ab95190e6f3b709be97
  - [x] https://github.com/Yunite-Net/yunite.me/pull/3
  - [x] `https://yunite.me/terms-and-conditions` → `https://yunite.org/nutzungsbedingungen/`
  - [x] `https://yunite.me/data-privacy` → `https://yunite.org/datenschutz/`

**Comment by Tirokk** [comment]
Solved by #6441 and in future by https://github.com/Yunite-Net/yunite.me/pull/3
