### ISSUE TITLE
🚀 [Feature][Webapp] Yunite – Add a submenu to the Content Menu on the Yunite.org header

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#6473]
## 🚀 Feature

Yunite – Add a submenu to the Content Menu on the Yunite.org header.

Sub menu has post types and after a seperation line the display types.

- [ ] by selecting the top level title `Content` visite a new side on Yunite.org which describes the post types and may be the display types like newsfeed, map (and, calendar later)
- [ ] by selecting a post type or display type go to Yunite.me with a query in the url that sets the filters or visits the display type
- [ ] same by clicking on one of the described post types on Yunite.org

### Todo

- Example for the post type query: `https://yunite.me/?postType=Event`

<img width="1005" alt="Bildschirmfoto 2023-06-21 um 11 45 52" src="https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/25344101/0ba27e17-d75e-4d58-adea-cbe19ec26a35">
