### ISSUE TITLE
🔧 [Refactor][Frontend] Filter menu optimisation

### ISSUE THREAD

**Issue by Elweyn** [Ocelot-Social-Community/Ocelot-Social#6500]
## 🔧 Refactor issue
For the events the most important filter is the content type so we need it at the start of the filters.
The all button of topics should also be a square like the topics
Add headline for "Users I follow" / "My Groups" EN: Sources / DE: Quellen
![image](https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/33051975/834d87d6-7eea-4fc3-bfe3-9a6f1a878932)

## 🤖 ToDos:
Filter Menu

- [x] Filter menu content type as first
- [x] Filter menu „All“ button for topic shown as square
- [x] Filter menu remove hr line
- [x] Filter menu 2nd headline EN: Sources / DE: Quellen
- [x] Filter menu "Users I follow" and "My groups" as square
- [x] Filter menu "Nutzer, denn ich folge", "meine Gruppen"
- [x] Filter menu "Zukünftige" statt "nicht beendete"

Filter Buttons

- [x] Filter button remove text EN:"Only" / DE:"Nur"
- [x] Filter button Text: "Inhalt filtern" should be "Inhalte filtern"
