### ISSUE TITLE
🚀 [Feature][Webapp] On open ``/chat`` page close mini chat window

### ISSUE THREAD

**Issue by Elweyn** [Ocelot-Social-Community/Ocelot-Social#6589]
## 🚀 Feature

When I go on the ``/chat`` page it is strange to see the mini chat still open.
Would be nice if the mini chat would be closed when the overview of chats is opened.

## 🤖 ToDo

- [x] Close mini chat when opening `/chat` page
  - [ ] select the former chat partner on the mini chat on the `/chat` page
    - [ ] room on `/chat` page is not selected yet
    - [ ] especially if the room is not loaded already
- [x] on clicking the chat button on a new user profile and → change mini chat partner to actual profile
