### ISSUE TITLE
🚀 [Feature] Select Former Chat Room in List if Visiting Chat Room Page with Open Small Chat that Closes

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#6606]
## 🚀 Feature

Select Former Chat Room in List if Visiting Chat Room Page with Open Small Chat that Closes.

### Todo

- on closing small chat when opening `/chat` page
  - [ ] select the former chat partner of the small chat on the `/chat` page
    - [ ] room on `/chat` page is not selected yet
    - [ ] especially if the room is not loaded already
