### ISSUE TITLE
🔧 [Refactor][Webapp] User Name and Slug shall have Const for their Length with 3 Characters

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#6636]
## 🔧 Refactor ticket

User Name and Slug shall have Const for their Length with 3 Characters.

### Todo

First implement constant in (new) files `webapp/constants/user.js` and `XXX`:

```js
export const NAME_LENGTH_MIN = 3
export const NAME_LENGTH_MAX = 50
export const SLUG_LENGTH_MIN = 3
export const SLUG_LENGTH_MAX = 50
```

And use it at:

- [ ] webapp:
  - [ ] `webapp/components/Registration/RegistrationSlideCreate.vue`
  - [ ] `webapp/pages/settings/index.vue` for user name
    - [ ] implement new? `webapp/components/utils/UniqueSlugForm.js` for user slug
  - [ ] `components/generic/SelectUserSearch/SelectUserSearch.vue`
- [ ] backend:
  - [ ] `backend/src/middleware/validation/validationMiddleware.ts`
    - [ ] `backend/src/middleware/validation/validationMiddleware.spec.ts`
  - [ ] check for the slug length?
