### ISSUE TITLE
🐛 [Bug][Webapp/Backend] Chat – On Deleting the User Account Probably the Content of the Messages is not set to Empty

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#6657]
## 🐛 Bugreport

On Deleting the User Account Probably the Content of the Messages is not set to Empty

### Todo

On Deleting a User Account:

- [ ] set the content of a message to be empty
- [ ] mark the messages as deleted
- [ ] handle the displaying of deleted messages
