### ISSUE TITLE
💥 [DevOps][Deployment] Solving Neo4j v3 to v4 Transition Problems

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#6663]
## 💥 DevOps ticket

Solving Neo4j v3 to v4 Transition Problems.

### Additional Information

https://neo4j.com/docs/upgrade-migration-guide/current/version-4/migration/migrate-to-4.x/standalone/

### Todo

- [ ] have a fixed Neo4j version tag on the servers instead of `latest`?

… or …

- [ ] have a different main name for now like `ocelotsocialnetwork/neo4j-community-v4.4`

And:

- [ ] have a despription what to do to convert the database and add a hint to `deployment/TODO-next-update.md`
  - [ ] can we automate this?

**Comment by Tirokk** [comment]
Is solved
