### ISSUE TITLE
🐛 [Bug][DevOpts] Deployment - Some Scripts are not Working Because of Inventing TypeScript

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#6791]
## 🐛 Bugreport

Some Scripts are not Working Because of Inventing TypeScript.

### Todo

- [ ] in `backend/package.json`:
  - [ ] `prod:migrate`
  - [ ] ? `start`
- [ ] in `deployment/src/kubernetes/README.md`
  - [ ] see: `reset and seed Neo4j database via backend for staging`
