### ISSUE TITLE
🐛 [Bug][DevOps] Fix Broken Links and Content in Readmes – Part 2

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#6810]
## 🐛 Bugreport

Fix Broken Links and Content in Readmes – Part 2.

### Todo

- [ ] summary:
  - [ ] move `edit instructions` to the end of list?
  - [ ] add `[Docker More Closely](DOCKER_MORE_CLOSELY.md)` again as the one in the deployment folder
- [ ] check all what was not checked in #6802 
  - [ ] setcopyright to current year in [LICENSE.md](https://github.com/Ocelot-Social-Community/Ocelot-Social/blob/master/LICENSE.md) and elsewhere
