### ISSUE TITLE
🌟 [EPIC] Webapp: Overview in list 

### ISSUE THREAD

**Issue by Elweyn** [Ocelot-Social-Community/Ocelot-Social#6826]
## 🌟 EPIC

On the network sender.fm, Heimo which to have a list view instead of the grid view!
He wants to give the user the possibility to switch between both views.

For the list view the post card should be from left to right:
- First item picture that is always of same size, if picture is present else we need a placeholder to not break the list view
- Second part would be the user that created the post
- Third part would be the title and the description preview
- On the bottom right we need the buttons (Viewed, Clicked, Liked, ...)
- The ribbon can be at the end of the card with the collor of the post (Blue for article, Purple for event, ...)

## 🤖 ToDos
- [ ] 🚀 [Feature] Webapp: add buttons in filter to switch between both views
- [ ] 🚀 [Feature] Webapp: change overview layout to a list of posts
- [ ] 🚀 [Feature] Backend: store the user selection of overview layout

**Comment by Elweyn** [comment]
Frontend: @maeckes-infinitylabs etwa ~20 Std
- New component ~"ListItemCard"
- Enum for selection of NewsFeed layout view ("GridView" || "ListView")
- NewsFeed switch case between Views
- Unit-Test
Backend: ~4 Std
- Storage of Enum on User preference @Mogge, @maeckes-infinitylabs
  - Mutation: For switch between views
  - Query: At start of application
- Unit-Test

Total time: 24 Std

**Comment by Elweyn** [comment]
David hatte diese mockups geschickt 

Größere Bildschirme 
![list-view-item-desktop_20231120140706.png](https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/33051975/4f2b5d52-f977-4c7d-8f0a-db443e433b34)

Kleinere Handies
![list-view-item-small-screen-size_20231120140656.png](https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/33051975/f0ab0745-52d7-4654-9217-92e2ede9aa2b)

**Comment by Elweyn** [comment]
@Tirokk 

Bei großen Bilder sehen wir eine schwierigkeit, Lösung:
- Das Bild raus zoomen, um rum das Bild geblürten ☑️
- Das Bild ausschneiden
- Garkein Bild zeigen

Bei Posts wo keine Bilder sehen wir eine Schwierigkeit, Lösung:
- Ein ausgegraut Bild mit ein Durchgestrichenen Fotoaparat ☑️
- Eine random Farbkasten
- Ein Kasten mit einem Farbzwischt
