### ISSUE TITLE
🐛 [Bug][Deployment] Configurations in `deployment\constants\.` are not used in Backend by Dockerfile.

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#6851]
## 🐛 Bugreport

Configurations in `deployment\constants\.` are not used in backend by Dockerfile.

### Todo

- [ ] configurations in `deployment\constants\.` are not used in backend by Dockerfile?
  - [ ] it's not working for `groups.ts` and `DESCRIPTION_WITHOUT_HTML_LENGTH_MIN` at the end
  - [ ] may it be that the copy command is missing in the backends Dockerfile?
    - in the webapp it's:

```dockerfile
# Copy static files
# TODO - this seems not be needed anymore for the new rebranding
# TODO - this should be one Folder containign all stuff needed to be copied
COPY --from=build ${DOCKER_WORKDIR}/config/ ./config/
COPY --from=build ${DOCKER_WORKDIR}/constants ./constants
COPY --from=build ${DOCKER_WORKDIR}/static ./static
COPY --from=build ${DOCKER_WORKDIR}/locales ./locales
```

Please discuss with @Tirokk and @ulfgebhardt !!!
