### ISSUE TITLE
🌟 [EPIC] ActivityPub

### ISSUE THREAD

**Issue by Elweyn** [Ocelot-Social-Community/Ocelot-Social#6852]
## 🌟 EPIC

Ocelot-Social is a decentral Social Media Platform that has multiple instances.
Since it has multiple instance it would be interesting to have a protocoll to share posts between them.
A possible protocoll would be ActivityPub (Fediverse)

## 🤖 ToDos
- [ ] 💬 [Question] Reasearch: Is AcitivityPub the right protocoll to share posts between instances
- [ ] 🚀 [Feature] Backend: Implement the protocoll
- [ ] 🚀 [Feature] Frontend: Admin interface to enter the instance to import posts from
