### ISSUE TITLE
💥 [DevOps] Refine Automatic Backup Script `clusters.cron-backups.sh`

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#6870]
## 💥 DevOps ticket

Refine Automatic Backup Script `clusters.cron-backups.sh`.

### Todo

- [ ] change automatic backups on backup server
- [ ] before deleting old backups:
  - [ ] check if the dump and the images are really in the backup folder
    - [ ] check `neo4j-dump` file
    - [ ] check `public-uploads` folder?
      - [ ] log images count? then one can see if it is growing and gives a feeling for the total size
  - [ ] if not:
    - [ ] log this
    - [ ] send an e-mail?
    - [ ] what todo then? be aware of letting the volumen not running over
      - [ ] only count unbroken backups?
      - [ ] omit the actual backup folder to avoid that broken backups are deleted in favor of healthy ones?
