### ISSUE TITLE
🌟 [EPIC] Frontend – Migration Webapp (Nuxt + Vue2) zu Frontend (Vue3 + Vike)

### ISSUE THREAD

**Issue by Elweyn** [Ocelot-Social-Community/Ocelot-Social#6951]
## 🌟 EPIC

The technologies Nuxt and Vue2 are coming in end of life so we need to migrate it to Vu3.
As group we setup a Vike + Vue3 template and want to use this to create the new Frontend.

## 🤖 ToDos
- [ ] Setup Frontend Folder with Vu3 & Vike

### Pages:
- [ ] Create the Login Page
- [ ] Create the Register Page
- [ ] Create the Opt-In Page
- [ ] Create the Enter User Data Page
- [ ] Create the Confirm Create User Account Page
- [ ] Create the Reset Password Page
- [ ] Create the Change Password Page
- [ ] Create the Home (NewsFeed) Page
- [ ] Create the Create Post Page
- [ ] Create the View Post Page
- [ ] Create the Edit Post Page
- [ ] Create the User Profile Page
- [ ] Create the User Setting Page
- [ ] Create the Group List Page
- [ ] Create the Create Group Page
- [ ] Create the Group View Page
- [ ] Create the Group Setting Page
- [ ] Create the Map View Page
- [ ] Create the Chat Page
- [ ] Create the Moderation Page
- [ ] Create the Administration Page

### Atoms:
- [ ] Create the Logo Component
  - Big Logo
  - Small Logo
- [ ] Create the Language Switch Component
- [ ] Create the InputField Component
  - Text
  - Number
  - EMail
  - Password
  - Check Box
  - Date
  - Drop Zone
  - Combo Box
  - Address
  - Drop Down
  - Edit Field
- [ ] Create the Button Component
- [ ] Create the Link Component
- [ ] Create the Headline Component
- [ ] Create the Paragraph Component
- [ ] Create the Animation Component
- [ ] Create the Progression Bar Component
- [ ] Create the User Profil Image Component
  - User Profil
  - Group Profil
  - Post Teaser
- [ ] Create the Ribon Component
- [ ] Create the Show Date Component
- [ ] Create the Show Location Component
- [ ] Create the Label (Text with Color as Background) Component

### Molecules:
- [ ] Create the Header Component
- [ ] Create the Footer Component
- [ ] Create the NavBar Component
- [ ] Create the Enter Password Component
- [ ] Create the Donate Component
- [ ] Create the Post Teaser Component
- [ ] Create the Labeled InputField Component
- [ ] Create the Popover Component
  - User Profil in Header
  - Filter
- [ ] Create the User Teaser Component (Post or Group)
- [ ] Create the Masonary Grid Component
- [ ] Create the List of User Component (Follow, Following)
- [ ] Create the Group Teaser Component
- [ ] Create the List Group Component
- [ ] Create the Profil View Component (User, Group)
  - Picture
  - Name
  - Created
  - ...
- [ ] Create the Table Component
- [ ] Create the Map Component
- [ ] Create the Chat Component
