### ISSUE TITLE
🚀 [Feature] Replace checkbox by toggle switch

### ISSUE THREAD

**Issue by sushidave** [Ocelot-Social-Community/Ocelot-Social#7603]
## 🚀 Feature

On some pages of the account settings the checkbox and Save button should be replaced by a toggle switch:
- Privacy
- Third-party provider
- Notifications

This is in line with UX best practices: https://uxmovement.com/buttons/when-to-use-a-switch-or-checkbox/

It simplifies the handing for users as it only requires one action instead of two.

### Tasks
- [ ] Replace the checkbox by a toggle switch
- [ ] Make the settings save instantly if using the switch.
- [ ] Delete the Save button as it's no longer needed.
